<!doctype html>
<html lang="ar" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#102541"><title>WolFox — أدوات IPA</title><link rel="stylesheet" href="assets/app.css"><script src="assets/app.js" defer></script></head>
<body>
<header class="topbar"><a class="brand" href="index.php"><span class="mark" aria-hidden="true">W</span><span dir="ltr">WolFox <small>3.0.0</small></span></a><div class="top-end"><span class="private"><i></i> مساحة خاصة</span><?php if (signedIn()): ?><form action="?action=logout" method="post"><input type="hidden" name="csrf" value="<?= e($_SESSION['csrf']) ?>"><button class="quiet" type="submit">تسجيل الخروج</button></form><?php endif ?></div></header>
<main class="<?= signedIn() ? 'dashboard' : 'login-wrap' ?>">
<?php if (!signedIn()): ?>
<section class="login-intro"><span class="eyebrow">أدواتك، في مكان واحد</span><h1>مساحتك الخاصة<br>لتجهيز التطبيقات.</h1><p>ارفع ملف IPA، أضف مكتباتك عند الحاجة،<br>واحتفظ برابط تنزيل خاص لكل نتيجة.</p><div class="intro-line"><span>رفع</span><b>←</b><span>دمج اختياري</span><b>←</b><span>تنزيل</span></div></section>
<section class="panel login"><div class="section-icon" aria-hidden="true">W</div><h2>أهلًا بك في WolFox</h2><p class="muted">سجّل الدخول إلى لوحة أدواتك.</p>
<?php if ($error): ?><p class="notice danger" role="alert"><?= e($error) ?></p><?php endif ?>
<?php if (!$configured): ?><p class="notice danger">الحساب غير مُعدّ. أكمل إعداد الحساب على الخادم أولًا.</p><?php endif ?>
<form action="?action=login" method="post" class="stack"><input type="hidden" name="csrf" value="<?= e($_SESSION['csrf']) ?>"><label for="username">اسم المستخدم</label><input id="username" name="username" placeholder="أدخل اسم المستخدم" autocomplete="username" required maxlength="100"><label for="password">كلمة المرور</label><input id="password" type="password" name="password" placeholder="أدخل كلمة المرور" autocomplete="current-password" required maxlength="1024"><button class="primary" type="submit">دخول إلى اللوحة <span aria-hidden="true">←</span></button></form><p class="login-foot">الوصول إلى الملفات يتطلب تسجيل الدخول.</p></section>
<?php else: ?>
<div class="page-heading"><div><span class="eyebrow">لوحة الأدوات</span><h1>جهّز ملفك، بخطوات واضحة.</h1><p class="muted">رفع آمن ومعالجة خاصة وروابط تنزيل في مكان واحد.</p></div><span class="user-chip">مرحبًا، <?= e($config['username']) ?></span></div>
<?php if ($error): ?><p class="notice danger" role="alert"><?= e($error) ?></p><?php endif ?>
<div class="workspace"><section class="panel upload-panel"><div class="section-heading"><span class="step">01</span><div><h2>رفع وتجهيز IPA</h2><p class="muted">اختر الملف من جهازك أو أدخل رابطه المباشر.</p></div></div>
<form id="upload-form" action="?action=upload" method="post" enctype="multipart/form-data" class="stack"><input type="hidden" name="csrf" value="<?= e($_SESSION['csrf']) ?>">
<label class="dropzone" for="ipa"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M12 16V3m-5 5 5-5 5 5M4 14v6a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-6"/></svg><strong>اختر ملف IPA</strong><span>أو اسحبه إلى هنا · حتى 512 ميجابايت</span><input id="ipa" type="file" name="ipa" accept=".ipa"><span id="ipa-name" class="file-caption">لم يُحدد ملف بعد</span></label>
<div class="divider"><span>أو استخدم رابطًا مباشرًا</span></div><label for="url">رابط ملف IPA <span class="optional">اختياري عند اختيار ملف</span></label><input id="url" name="url" type="url" dir="ltr" placeholder="https://example.com/application.ipa" maxlength="4096" inputmode="url"><p class="field-note">رابط HTTPS مباشر للملف، دون تسجيل دخول.</p>
<div class="merge-head"><h3>ملفات الدمج</h3><span class="badge">اختيارية</span></div><label class="library-picker" for="libraries"><span class="plus" aria-hidden="true">+</span><span><strong>إضافة مكتبات dylib</strong><small>حتى 8 ملفات · 32 ميجابايت لكل ملف</small></span><input id="libraries" type="file" name="libraries[]" accept=".dylib" multiple></label><div id="library-names" class="file-caption" aria-live="polite">يمكنك ترك هذه الخانة فارغة.</div>
<p class="notice">بدون مكتبات: يُحفظ IPA كما هو. عند الدمج: تحتاج النتيجة إلى توقيع متوافق قبل التثبيت.</p><button id="submit-upload" type="submit" class="primary">تجهيز الملف وإنشاء الرابط <span aria-hidden="true">←</span></button><noscript><p class="notice danger">فعّل JavaScript لإظهار تقدّم الرفع ونتيجة المعالجة.</p></noscript>
</form><div id="progress-area" hidden><div class="progress-label"><strong id="progress-label">جارٍ رفع الملف…</strong><span id="progress-value">0%</span></div><progress id="progress" max="100" value="0">0%</progress><p class="muted">اترك الصفحة مفتوحة حتى ظهور النتيجة.</p></div><div id="upload-error" class="notice danger" role="alert" hidden></div>
</section><aside class="side-stack"><section class="panel result-panel"><div class="section-heading"><span class="step">02</span><div><h2>نتيجة المعالجة</h2><p class="muted">رابطك يظهر هنا عند اكتمال التجهيز.</p></div></div><div id="result-empty" class="empty-result"><span class="file-symbol" aria-hidden="true">IPA</span><h3>بانتظار ملفك</h3><p>حدد ملفًا، وأضف مكتباتك إن أردت،<br>ثم اضغط زر التجهيز.</p></div><div id="result" hidden><span id="result-mode" class="badge success"></span><h3 id="result-app"></h3><p id="result-bundle" class="muted ltr"></p><p id="result-size" class="muted"></p><p id="result-note" class="notice"></p><label for="result-link">رابط التنزيل الخاص</label><input id="result-link" readonly dir="ltr"><div class="result-actions"><a id="download-link" class="primary" href="#">تنزيل IPA</a><button id="copy-link" class="secondary" type="button">نسخ الرابط</button></div><p id="copy-feedback" class="field-note" aria-live="polite"></p><details><summary>بصمة الملف ومكتباته</summary><p id="result-hash" class="hash ltr"></p><pre id="result-libraries"></pre></details><a href="index.php" class="text-link">تحديث قائمة الملفات</a></div></section><section class="help-panel"><h3>خاص بك من الرفع إلى التنزيل</h3><p>روابط النتائج تتطلب الدخول، وتنتهي بعد <?= e($config['retention_hours']) ?> ساعة. يمكنك حذف ملفاتك في أي وقت.</p><p>يدعم الدمج تطبيقات arm64 غير المشفّرة ومكتبات dylib المتوافقة. لا تنفّذ الصفحة محتوى الملفات المرفوعة.</p></section></aside></div>
<section class="panel history"><div class="section-heading"><span class="step">03</span><div><h2>ملفاتي الأخيرة</h2><p class="muted">نتائجك المتاحة للتنزيل.</p></div><span class="count"><?= count($history) ?></span></div><?php if (!$history): ?><p class="muted history-empty">لا توجد ملفات جاهزة بعد. ابدأ برفع أول ملف.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>التطبيق</th><th>الحالة</th><th>الحجم</th><th>الإجراءات</th></tr></thead><tbody><?php foreach ($history as $item): ?><tr><td><strong><?= e($item['app']) ?></strong><small dir="ltr"><?= e($item['bundle']) ?></small></td><td><span class="badge <?= $item['mode'] === 'unchanged' ? '' : 'amber' ?>"><?= $item['mode'] === 'unchanged' ? 'دون تعديل' : 'مدمج · يحتاج توقيعًا' ?></span></td><td><?= number_format($item['size'] / 1048576, 1) ?> MB</td><td><div class="row-actions"><a class="text-link" href="?action=download&amp;id=<?= e($item['id']) ?>">تنزيل</a><button class="quiet copy-history" data-link="index.php?action=download&amp;id=<?= e($item['id']) ?>" type="button">نسخ الرابط</button><form action="?action=delete" method="post"><input type="hidden" name="csrf" value="<?= e($_SESSION['csrf']) ?>"><input type="hidden" name="id" value="<?= e($item['id']) ?>"><button class="delete" type="submit">حذف</button></form></div></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
<?php endif ?>
</main><footer><span dir="ltr">WolFox · 3.0.0</span><span>لوحة أدوات خاصة</span></footer>
</body></html>
